import {
    backgroundParams,
    breathConfig,
    creationLinkParams,
    distortionParams,
    fieldParams,
    flowParams,
    fluidParams,
    liquidParams,
    plasmaParams,
    quantumWaveParams,
    sceneParams,
    toggles,
} from './config.js';

const HOLD_PRESET = {
    toggles: {
        background: true,
        field: false,
        flowObjects: true,
        fog: true,
        fovBreath: true,
        htmlBreath: true,
        autoRotate: false,
        postProcess: true,
        fluidField: true,
        liquid: true,
        heatHaze: false,
        dof: true,
        quantumWave: true,
        showPlasma: false,
    },
    sceneParams: {
        mixCycle: 16.0,
        styleCycle: 22.0,
        fogDensity: 0.016,
        camX: -14,
        camY: 0,
        camZ: 80.0,
        camTargetY: -1,
    },
    fieldParams: {
        intensity: 1.0,
        alpha: 0.36,
        lineLow: 0.36,
        lineHigh: 0.78,
        bottomClip: 0.24,
        bottomFeather: 0.22,
    },
    flowParams: {
        seedOpacity: 0.82,
        filamentOpacity: 1.0,
        seedDrift: 2.26,
        chaos: 2.44,
        bundleTightness: 1.26,
        centerBandRatio: 0.745,
        centerThickness: 0.97,
        depthScatter: 1.28,
        speed: 1.0,
    },
    plasmaParams: {
        coreOpacity: 0.0,
        chaosOpacity: 0.0,
        radius: 14.0,
        chaos: 0.6,
        speed: 0.8,
        heightRatio: 0.6,
        autoChaosAmp: 30.0,
        wSeparation: 0.35,
        projectionScale: 0.4,
        colorA: 8172519,
        colorB: 13363187,
    },
    backgroundParams: {
        centerR: 0.0,
        centerG: 0.045,
        centerB: 0.19,
        edgeR: 0.003,
        edgeG: 0.14,
        edgeB: 0.2,
        pulse: 0.72,
        opacity: 0.82,
        tubeRadius: 89.5,
        tubeLength: 768.0,
        tubeFlowSpeed: 0.031,
        tubeNoiseScale: 4.36,
        tubeWarpStrength: 1.21,
        tubeSoftness: 0.85,
        tubeDepthFade: 0.78,
        tubeBrightness: 0.62,
        tubeSwirl: 2.5,
        starOpacity: 0.84,
        starSoftness: 7.0,
        starSize: 1.15,
    },
    fluidParams: {
        force: 1.0,
        curl: 1.0,
        decay: 0.948,
        radius: 0.21,
        influence: 0.06,
    },
    liquidParams: {
        textureSize: 128,
        timestep: 0.001,
        dissipation: 0.904,
        iterations: 12,
        forceRadius: 0.08,
        forceStrength: 4.5,
        splatGain: 5.0,
        densityMul: 1.8,
        noiseScale: 9.5,
        noiseSpeed: 0.02,
        noiseAmp: 0.1,
        specularPow: 8.0,
        specularInt: 1.8,
        normalZ: 0.3,
        diffuseGain: 0.3,
        densityEdge: 0.5,
        alphaEdge: 0.3,
        alphaMax: 0.9,
        refractOffsetScale: 0.055,
        refractThreshold: 0.006,
        baseColorR: 0.8,
        baseColorG: 0.85,
        baseColorB: 0.85,
        highlightR: 0.9,
        highlightG: 0.9,
        highlightB: 0.9,
    },
    creationLinkParams: {
        sizeGain: 5.81,
        linkSpread: 2.96,
        linkDepthSpread: 1.57,
        pulseSpeed: 1.43,
        vortexSpeed: 0.42,
        swirlStrength: 0.83,
        sphereFill: 0.3,
        colorSplitSoftness: 0.245,
        particleBrightness: 1.7,
        particleSoftness: 5.48,
        coreSharpness: 0.72,
        fluidDrift: 0.52,
        pointerBurstStrength: 1.0,
        pointerBurstSpread: 20.0,
        colorContrast: 1.26,
        floatAmp: 0.32,
        floatOffset: -0.1,
        yawSpeed: 0.24,
        tiltSpeed: 1.55,
        tiltAmp: 0.1,
        baseScaleMul: 1.95,
        pulseScaleAmp: 0.32,
        hoverScaleBoost: 0.48,
        hoverLerp: 0.025,
        pointAlpha: 0.18,
        shellOpacityBase: 0.78,
        shellOpacityPulse: 0.84,
        shellOpacityHover: 0.7,
        shellSpinSpeed: 1.49,
        haloScalePulse: 0.39,
        haloScaleHover: 2.17,
        haloOpacityBase: 0.34,
        haloOpacityPulse: 0.92,
        haloOpacityHover: 0.45,
        link1PosX: -9.0,
        link1PosY: -2.1,
        link1PosZ: -8.0,
        link1Scale: 10.0,
        link1GlowScale: 4.8,
        link1HitRadius: 2.0,
        link1Phase: 0.15,
        link1ColorAR: 1.0,
        link1ColorAG: 1.0,
        link1ColorAB: 1.0,
        link1ColorBR: 0.06,
        link1ColorBG: 0.72,
        link1ColorBB: 0.72,
        link2PosX: 0.1,
        link2PosY: -0.8,
        link2PosZ: -9.4,
        link2Scale: 10.0,
        link2GlowScale: 5.2,
        link2HitRadius: 2.2,
        link2Phase: 1.4,
        link2ColorAR: 1.0,
        link2ColorAG: 1.0,
        link2ColorAB: 1.0,
        link2ColorBR: 0.06,
        link2ColorBG: 0.72,
        link2ColorBB: 0.72,
        link3PosX: 9.2,
        link3PosY: -1.95,
        link3PosZ: -7.1,
        link3Scale: 10.0,
        link3GlowScale: 4.5,
        link3HitRadius: 1.95,
        link3Phase: 2.8,
        link3ColorAR: 1.0,
        link3ColorAG: 1.0,
        link3ColorAB: 1.0,
        link3ColorBR: 0.06,
        link3ColorBG: 0.72,
        link3ColorBB: 0.72,
    },
    quantumWaveParams: {
        strength: 0.032,
        speed: 0.24,
        baseFreq: 2.4,
        dispersion: 0.11,
        noiseAmp: 0.25,
        noiseScale: 2.1,
        waveCount: 8.0,
        envelope: 0.82,
        yInfluence: 0.7,
        glowAmount: 0.0,
        glowColorR: 0.45,
        glowColorG: 0.72,
        glowColorB: 1.0,
        caberration: 0.0,
        rimBright: 0.0,
        blurAmount: 0.0,
        fogDensity: 0.0,
        fogColorR: 0.34,
        fogColorG: 0.46,
        fogColorB: 0.62,
        darken: 0.0,
        turbulence: 0.0,
        sharpness: 0.74,
    },
    distortionParams: {
        strength: 0.03,
        aberration: 0.1,
        turbulence: 0.4,
        baseBlur: 0.06,
        blurAmount: 0.15,
        innerGlow: 0.1,
        haloIntensity: 0.2,
        haloWidth: 1.0,
        haloColorR: 0.3,
        haloColorG: 0.2,
        haloColorB: 0.05,
        heatHaze: 0.024,
        heatHazeRadius: 0.5,
        heatHazeSpeed: 1.0,
        dofStrength: 0.006,
        dofFocusRadius: 0.26,
    },
    breathConfig: {
        period: 8.0,
        htmlMinOpacity: 0.1,
        htmlMaxOpacity: 0.8,
        htmlMaxBlur: 3.0,
        htmlMinScale: 0.95,
        fovBase: 60.0,
        fovAmplitude: 1.0,
    },
};

const WABI_PRESET = {
    toggles: {
        background: true,
        field: true,
        flowObjects: true,
        fog: true,
        fovBreath: true,
        htmlBreath: true,
        autoRotate: false,
        postProcess: true,
        fluidField: true,
        liquid: false,
        heatHaze: false,
        dof: true,
        quantumWave: true,
        showPlasma: true,
    },
    sceneParams: {
        mixCycle: 16,
        styleCycle: 22,
        fogDensity: 0.008,
        camX: -2,
        camY: 0,
        camZ: 38,
        camTargetY: -2,
    },
    fieldParams: {
        intensity: 1.2,
        alpha: 0.42,
        lineLow: 0.3,
        lineHigh: 0.72,
        bottomClip: 0,
        bottomFeather: 0.15,
    },
    flowParams: {
        seedOpacity: 0.53,
        filamentOpacity: 0.5,
        seedDrift: 1.34,
        chaos: 1.8,
        bundleTightness: 0.25,
        centerBandRatio: 0.25,
        centerThickness: 0.97,
        speed: 1,
    },
    plasmaParams: {
        coreOpacity: 0.04,
        chaosOpacity: 0.15,
        radius: 5,
        chaos: 50,
        speed: 0.65,
        heightRatio: 0.6,
        autoChaosAmp: 80,
        wSeparation: 1.2,
        projectionScale: 1.2,
        colorA: 8172519,
        colorB: 13363187,
    },
    backgroundParams: {
        centerR: 0.042,
        centerG: 0.041,
        centerB: 0.066,
        edgeR: 0.041,
        edgeG: 0.168,
        edgeB: 0.268,
        pulse: 0.105,
        opacity: 1,
    },
    fluidParams: {
        force: 1,
        curl: 1,
        decay: 0.948,
        radius: 0.21,
        influence: 0.06,
    },
    liquidParams: {
        textureSize: 128,
        timestep: 0.001,
        dissipation: 0.904,
        iterations: 12,
        forceRadius: 0.08,
        forceStrength: 4.5,
        splatGain: 5,
        densityMul: 1.8,
        noiseScale: 9.5,
        noiseSpeed: 0.02,
        noiseAmp: 0.1,
        specularPow: 8,
        specularInt: 1.8,
        normalZ: 0.3,
        diffuseGain: 0.3,
        densityEdge: 0.5,
        alphaEdge: 0.3,
        alphaMax: 0.9,
        refractOffsetScale: 0.055,
        refractThreshold: 0.006,
        baseColorR: 0.8,
        baseColorG: 0.85,
        baseColorB: 0.85,
        highlightR: 0.9,
        highlightG: 0.9,
        highlightB: 0.9,
    },
    creationLinkParams: {
        pulseSpeed: 0.37,
        vortexSpeed: 0.92,
        swirlStrength: 0.26,
        sphereFill: 0.95,
        colorSplitSoftness: 0.08,
        particleBrightness: 0.72,
        particleSoftness: 3.2,
        fluidDrift: 0.14,
        pointerBurstStrength: 1,
        pointerBurstSpread: 20,
        colorContrast: 0.55,
        floatAmp: 0.25,
        floatOffset: -0.1,
        yawSpeed: 0.18,
        tiltSpeed: 0.3,
        tiltAmp: 0.08,
        baseScaleMul: 1,
        pulseScaleAmp: 0.065,
        hoverScaleBoost: 0.48,
        hoverLerp: 0.025,
        pointAlpha: 0.025,
        shellOpacityBase: 0.78,
        shellOpacityPulse: 0.84,
        shellOpacityHover: 0.7,
        shellSpinSpeed: 1.49,
        haloScalePulse: 0.39,
        haloScaleHover: 0.32,
        haloOpacityBase: 0.08,
        haloOpacityPulse: 0.28,
        haloOpacityHover: 0.34,
        link1PosX: 0,
        link1PosY: -1,
        link1PosZ: -2,
        link1Scale: 13,
        link1GlowScale: 6,
        link1HitRadius: 2.8,
        link1Phase: 0.15,
        link1ColorAR: 0.09,
        link1ColorAG: 0.22,
        link1ColorAB: 0.74,
        link1ColorBR: 0.84,
        link1ColorBG: 0.96,
        link1ColorBB: 1,
    },
    quantumWaveParams: {
        strength: 0.032,
        speed: 0.24,
        baseFreq: 2.4,
        dispersion: 0.11,
        noiseAmp: 0.25,
        noiseScale: 2.1,
        waveCount: 8,
        envelope: 0.82,
        yInfluence: 0.7,
        glowAmount: 0,
        glowColorR: 0.45,
        glowColorG: 0.72,
        glowColorB: 1,
        caberration: 0,
        rimBright: 0,
        blurAmount: 0,
        fogDensity: 0,
        fogColorR: 0.34,
        fogColorG: 0.46,
        fogColorB: 0.62,
        darken: 0,
        turbulence: 0,
        sharpness: 0.74,
    },
    distortionParams: {
        strength: 0.01,
        aberration: 0.03,
        turbulence: 0.1,
        baseBlur: 0.02,
        blurAmount: 0.05,
        innerGlow: 0.1,
        haloIntensity: 0.2,
        haloWidth: 1,
        haloColorR: 0.3,
        haloColorG: 0.2,
        haloColorB: 0.05,
        heatHaze: 0.024,
        heatHazeRadius: 0.5,
        heatHazeSpeed: 1,
        dofStrength: 0.006,
        dofFocusRadius: 0.26,
    },
    breathConfig: {
        period: 8,
        htmlMinOpacity: 0.1,
        htmlMaxOpacity: 0.8,
        htmlMaxBlur: 3,
        htmlMinScale: 0.95,
        fovBase: 60,
        fovAmplitude: 1,
    },
};

const INTENT_PRESET = {
    ...HOLD_PRESET,
    toggles: {
        ...HOLD_PRESET.toggles,
        background: false,
        field: false,
        flowObjects: false,
        fog: false,
        postProcess: false,
        fluidField: false,
        liquid: false,
        dof: false,
        quantumWave: false,
        showPlasma: false,
    },
    sceneParams: {
        ...HOLD_PRESET.sceneParams,
        camX: 0,
        camY: 4,
        camZ: 24,
        camTargetY: -2.6,
    },
    breathConfig: {
        ...HOLD_PRESET.breathConfig,
        fovAmplitude: 0.18,
    },
};

const SCENE_PRESETS = {
    hold: HOLD_PRESET,
    wabi: WABI_PRESET,
    intent: INTENT_PRESET,
};

function hashString(value) {
    let hash = 2166136261;
    for (let i = 0; i < value.length; i++) {
        hash ^= value.charCodeAt(i);
        hash = Math.imul(hash, 16777619);
    }
    return (hash >>> 0).toString(36);
}

function cloneValue(value) {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
        const out = {};
        Object.entries(value).forEach(([k, v]) => {
            out[k] = cloneValue(v);
        });
        return out;
    }
    return value;
}

export function getScenePreset(sceneName) {
    const preset = SCENE_PRESETS[sceneName] || SCENE_PRESETS.hold;
    return cloneValue(preset);
}

const SCENE_PRESET_VERSIONS = Object.fromEntries(
    Object.entries(SCENE_PRESETS).map(([sceneName, preset]) => [
        sceneName,
        hashString(JSON.stringify(preset)),
    ])
);

export function getScenePresetVersion(sceneName) {
    return SCENE_PRESET_VERSIONS[sceneName] || SCENE_PRESET_VERSIONS.hold;
}

function applyGroup(target, values) {
    Object.entries(values).forEach(([key, value]) => {
        const current = target[key];
        if (current && typeof current.setHex === 'function' && Number.isFinite(value)) {
            current.setHex(value);
            return;
        }
        target[key] = value;
    });
}

export function applyScenePreset(sceneName) {
    const preset = getScenePreset(sceneName);

    applyGroup(toggles, preset.toggles);
    applyGroup(sceneParams, preset.sceneParams);
    applyGroup(fieldParams, preset.fieldParams);
    applyGroup(flowParams, preset.flowParams);
    applyGroup(plasmaParams, preset.plasmaParams);
    applyGroup(backgroundParams, preset.backgroundParams);
    applyGroup(fluidParams, preset.fluidParams);
    applyGroup(liquidParams, preset.liquidParams);
    applyGroup(creationLinkParams, preset.creationLinkParams);
    applyGroup(quantumWaveParams, preset.quantumWaveParams);
    applyGroup(distortionParams, preset.distortionParams);
    applyGroup(breathConfig, preset.breathConfig);
}

export function resolveSceneVariant(graphicMode) {
    if (graphicMode === 'wabi') return 'wabi';
    if (graphicMode === 'intent') return 'intent';
    return 'hold';
}
