// Auto-updated by scripts/bump-dev-version.mjs via .githooks/pre-commit.
// Do not edit this file manually unless the hook/bootstrap is being repaired.
export const DEV_VERSION = 'v0.288.0';
export const DEV_VERSION_DATE = '2026-03-16';
